### PR TITLE
Removed abstract classes from Java impl

### PR DESCRIPTION
**Pull request by paoloambrosio**
As discussed in pull #21

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Making `Expr` an interface would be the right thing to do, but JFlex wants it to be a class. See Travis build.

**Comment by paoloambrosio** [comment]
Then I have a problem because I can run "mvn package" on the Java project without any problem and all the tests pass. The environment is Linux Mint 14 x32 with both Oracle Java and OpenJDK 7. I confess I haven't compiled JRuby (but just C, Java, JavaScript and Ruby).

I need to understand how to make it fail :-/

**Comment by aslakhellesoy** [comment]
Try `mvn clean package` maybe?

**Comment by paoloambrosio** [comment]
It was a totally different issue! `Binary` had been removed in the source tree, but its removal had not been included in the commit (the error was on `Binary` and not `Expr`). JFlex seems to be working with the interface.

**Pull request merged**
