### PR TITLE
Small Java implementation refactoring

### PR DESCRIPTION
**Pull request by paoloambrosio**
- Force compile checking for visitable nodes with abstract method
- Improved readability of Evaluator (inspired by the Ruby one)

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Good stuff. I actually removed the inheritance (The Binary class) from the C/Ruby code in f35fec3528470916d20758867e0d59042c4039c5 because I'm not a big fan of inheritance as a way to reduce duplication. I think it should only be used for polymorphic behaviour, and nothing uses `Binary` directly...

Want to remove that from Java too?

**Comment by mattwynne** [comment]
Nice refactorings :)

I was wondering why the interface is called `Expr` rather than `Node`. Is there a reason for that?

**Comment by aslakhellesoy** [comment]
`Expr` is short for Expression. We're dealing with boolean expressions ;-)

**Comment by paoloambrosio** [comment]
I personally like `Expr` instead of `Node` because everything is an expression, but it might be impossible to find a common name other than Node in Gherkin :-)

@aslakhellesoy the `Binary` class wasn't adding anything so i removed it with pull #26

**Pull request merged**
