### PR TITLE
Add Matt to Release Managers

### PR DESCRIPTION
**Pull request by mattwynne**

### CODE REVIEW

**Comment by mattwynne** [comment]
Waiting for sonatype rights, then I'll try and do a release.

**Comment by aslakhellesoy** [comment]
I've given you rubygems and npm karma. I'll wait with the merge until you have sonatype karma and done a full release.

**Comment by aslakhellesoy** [comment]
I ran:

```
npm owner add mattwynne bool
```

Listing it:

```
npm owner list bool
```

Lists your name, but it doesn't show up on https://npmjs.org/package/bool yet. Could be a caching issue. Let me know if you run into problems,

**Comment by mattwynne** [comment]
Nearly there, but got this trying to publish the npm package:

```
cd javascript && npm publish
npm ERR! need auth auth and email required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! System Darwin 12.2.0
npm ERR! command "/usr/local/Cellar/node/0.8.18/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/matt/projects/bool/javascript
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ENEEDAUTH
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/matt/projects/bool/javascript/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mattwynne** [comment]
Oh I actually read it now, and it looks like I need to do something here from my end. Hang on a tic...

**Comment by mattwynne** [comment]
Woo! Did it!

However, I was asked multiple times for my GPG key passphrase:

```
You need a passphrase to unlock the secret key for
user: "Matt Wynne <matt@mattwynne.net>"
1024-bit RSA key, ID 9EF9B071, created 2013-02-11

Enter passphrase: gpg: gpg-agent is not available in this session
```

Anything I can do about that?

**Comment by aslakhellesoy** [comment]
@mattwynne npm and rubygems packages seem to have been uploaded ok, but not the jars.

I can't see 1.0.4 here: https://oss.sonatype.org/content/repositories/releases/info/cukes/bool/

If you still have the output from your shell, please paste it here. You should have seen a bunch of "Uploading..." lines.

If you don't want to enter the password all the time, install a gpg agent and load your keys into it. I use http://gpgtools.org/keychain.html. If that works for you, please add to DEVELOPERS.md.

**Comment by mattwynne** [comment]
```
You need a passphrase to unlock the secret key for
user: "Matt Wynne <matt@mattwynne.net>"
1024-bit RSA key, ID 9EF9B071, created 2013-02-11

Enter passphrase: gpg: gpg-agent is not available in this session
[INFO] [install:install {execution: default-install}]
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4.jar to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4.jar
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4-sources.jar to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4-sources.jar
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4-javadoc.jar to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4-javadoc.jar
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4.jar.asc to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4.jar.asc
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4.pom.asc to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4.pom.asc
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4-sources.jar.asc to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4-sources.jar.asc
[INFO] Installing /Users/matt/projects/bool/java/target/bool-1.0.4-javadoc.jar.asc to /Users/matt/.m2/repository/info/cukes/bool/1.0.4/bool-1.0.4-javadoc.jar.asc
[INFO] [deploy:deploy {execution: default-deploy}]
Uploading: https://oss.sonatype.org/service/local/staging/deploy/maven2//info/cukes/bool/1.0.4/bool-1.0.4.jar
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error deploying artifact: Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/info/cukes/bool/1.0.4/bool-1.0.4.jar. Return code is: 401
```

I'll try the gpg agent thing now.

**Comment by aslakhellesoy** [comment]
It looks like you're not authenticating at sonatype - I don't think this is related to gpg signing at all. See http://www.sonatype.com/people/2010/11/what-to-do-when-nexus-returns-401/

**Comment by mattwynne** [comment]
Right this was me being stupid, and putting the settings.xml in `~/m2` instead of `~/.m2`

So I think I have deployed 1.0.4 to sonatype now. How would I check?

I'm going to try releasing 1.0.7 now, to see if I can make it work in one go.

**Comment by aslakhellesoy** [comment]
Good! Developers.md describes how to check

**Comment by mattwynne** [comment]
1.0.7 seemed to get messed up, but 1.0.8 is all mine!

**Comment by mattwynne** [comment]
Shite. That's what happens when you `git rebase master` instead of `git merge master` on a public commit.

**Pull request merged**
