### PR TITLE
small improvements for ruby build

### PR DESCRIPTION
**Pull request by os97673**
let call bundle install, and use bundle exec rake

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Weird that travis choked on this...

**Comment by os97673** [comment]
Yep :(  For some reason it was unable to clone repo.
Do you have any idea how to force it to restart build for the pull request?

**Comment by aslakhellesoy** [comment]
No idea.

**Comment by os97673** [comment]
Ok, I will try to close this pull request and file a new one.

**Pull request closed without merging**
